common: Fix parsing of wait option
Unlike its short form, the long form of the wait option requires an
argument. This breaks parsing when other options are combined. Make it
optional to fix such problems.

E.g.
  $ wb32-dfu-updater_cli --wait --upload /dev/null

Before:

  Error: Unexpected argument: /dev/null
  ...

After:

  Waiting for device, exit with ctrl-C
  ...

Signed-off-by: Sandipan Das <sandipan.osd@gmail.com>